name: Running Unit Tests and Reporting Coverage

on:
  pull_request:
    branches:
      - main

permissions:
  pull-requests: write

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4  # Updated to v4

      - name: Use Node.js 14.x
        uses: actions/setup-node@v4  # Updated to v4
        with:
          node-version: '14.x'

      - name: Install Dependencies
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install
          fi

      - name: Run Tests
        run: npm test

      - name: Upload Coverage Artifact
        uses: actions/upload-artifact@v4  # Updated to v4
        with:
          name: coverage
          path: ./coverage

      - name: Upload Test Results Artifact
        uses: actions/upload-artifact@v4  # Updated to v4
        with:
          name: test-results
          path: ./test-results
